### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by jeremyworger** [adriananders/JayMeter-Max4Live#1]
Hey, looks super sweet....im getting no sound, 
Is it because im using Live 10 which is 64 bit?
Or is it because JayMeter is 32-bit?

**Comment by adriananders** [comment]
Hi! Thank you for reaching out.

Can you clarify the issue? JayMeter by itself produces no sound because it is a Max For Live MIDI effect. So in order to hear a sound you will need to

1. Create a MIDI track
2. Create a brief MIDI phrase in either the clip or arranger.
3. Add a suitable instrument such as a drum rack or VST plugin.
4. Add JayMeter as a MIDI effect before the instrument in the channel.

I would advise playing some simple patterns through with no changes to the dial defaults. This will help root-cause the issue. If you're still having issues, bypass the MIDI effect entirely to see if it's an issue with the channel otherwise. If iJayMeter is not passing the notes through, please ping me again and I can look further into the issue. I want to guess based on your issue description that it's a misunderstanding about what JayMeter is designed to do. If that's the case, please let me know how I can clarify the project description.

Thanks!

**Comment by jeremyworger** [comment]
Sorry yes, I have done steps 1 through 4 already, 
I created a midi track, added some notes, then added a regular 808 kit  
This plays the notes I created (in a loop), and I hear sound.  
Then I added Jaymeter, and I no longer have any sound, so I am assuming its not passing the notes through.

**Comment by jeremyworger** [comment]
https://imgur.com/a/NM5CFrB  
https://imgur.com/a/TYmDk6m

**Comment by adriananders** [comment]
Great, I can look into this over the weekend. Two more questions. Are you on PC or Mac? Can you specify the specific OS version? Finally, did you edit and "unfreeze" the Max object? I want to reproduce the set of steps leading to your issue so i can solve it for others. Max For Live... is finicky.

**Comment by jeremyworger** [comment]
Cool. Windows 10, 64-bit. I'm using live 10 (also 64-bit).  
Yeah, I turned some knobs, and clicked pretty much everything. 
Dropping in JayMeter stopped the midi levels altogether.

**Comment by adriananders** [comment]
Oh, okay that might be the issue. I'll have to install Ableton and Max on Windows to see, but the latest version of JayMeter uses what's called [gen](https://docs.cycling74.com/max7/vignettes/gen_topic) which goes through a compilation step. Even though it's supposed to be cross-platform, it may require a compilation within Windows to fix the issue. I developed it in MacOS Catalina. If that's the case I'll compile a Windows version and upload it in the next revision later in the week. Thanks for your help bringing this issue up.

**Comment by jeremyworger** [comment]
Ahh. Yeah no problem, I definitely want to try it out, looks so rad!

**Comment by adriananders** [comment]
Hmmmm. I'm not able to reproduce your issue on my wife's Windows 10 64-bit machine with a fresh Ableton 10 with max for live 8 install, and a fresh pull of the patch from Github. Loaded up a 909 Core kit, created a sequence, then added the Jaymeter before the kit. No problems. Sound passes through and the effect works as I intended. I even opened up the effect, unfreezed the patch just in case that's what you did. Still works fine. So I'm not sure where to go from here. Max is painful to debug due to the lack of a dedicated testing and logging for patches outside of console print.

Just to clarify, you do own a copy of max for live for Ableton correct? I'm thinking of doing a video walkthrough with OOTB drumkits so that it's easy to follow the precise steps. Sorry I'm not able to resolve. I see that you've cloned. If you're able to root-cause and find a solution, please reach out and I'll try to get it into master. Thanks.

**Comment by adriananders** [comment]
Wow. I feel dumb. The latest change I made which fixes a bunch of issues was not pushed into master. I just did this. So let me test this version on my wife's machine.

**Comment by adriananders** [comment]
Okay, can you test the version I just pushed to master a few minutes ago? Hopefully that fixes your issue. Thanks.

**Comment by jeremyworger** [comment]
Hmm super weird, I tried the new pushed version and still nothing...I can apply the default max for live effects , like note echo for instance, and that works....I'm not sure, maybe im doing something extra stupid, I'll let you know if I figure it out haha
-The sound meter on the left side of Jaymeter is working now though, dont think it was doing that before...but no sound.

**Comment by jeremyworger** [comment]
I tried a different device and got no sound as well, so the problem is not on your end/with jaymeter.

**Comment by adriananders** [comment]
Awesome. Glad to hear it's not with my device. I think your best bet would be to check which version of max you are using (if it's 7, that would explain your errors - upgrade to 8 would probably solve). I would also pursue the Cycling 74 forums [Max for Live](https://cycling74.com/forums/category/Max%20For%20Live/page/1) forum as those folks would know far better than me what could be causing your issues with other folk's devices. In fact the Cycling/Ableton devs are routinely in that forum and could perhaps diagnose the problem better than I can. If one of the official Max For Live patches are also not working, you could try reaching out to Ableton or Cycling74's technical support and they may be able to help as well. If all else fails, try a clean install of Ableton to see if that fixes the issue (just be sure to backup your settings and content first!). Thanks for your issue ticket. This issue did help me as I pushed a version that I forgot to several weeks ago. Good luck!

**Comment by jeremyworger** [comment]
Sorry to bother again, I never figured out how to fix my issue....is it possible to just run the plugin in Max on its own? Or did you write a max-only version of Jaymeter?

**Comment by jeremyworger** [comment]
I have it like: https://imgur.com/a/OWcXU1H  
The midi goes through (from a midi file looping in audacity) and then out to my drum machine.....but turning the knobs in jaymeter does nothing :<

**Comment by adriananders** [comment]
Oh, yea. It's not likely to run in standalone for the following reasons:
- plugsync which determines playback position only operates in Max For Live mode.
- Sequencer itself does not free-run. It's dependent upon the playback mode of Live in order to operate.

 I may build a free-running mode and/or standalone in free-running mode at some point. Right now I'm working on a tempo automation tool. After I get done with that I may look into this enhancement. Thanks.

**Comment by jeremyworger** [comment]
Ah I see. Well thanks for getting back to me! That would be super sweet, i'll keep an eye out for it if you end up adding it.

**Comment by jeremyworger** [comment]
I'm wondering if maybe in the future it might be possible to create the same jaymeter, but for audio drum loops instead of midi ones....one thing I had found was: 
http://smc.inesctec.pt/technologies/loopalooza/  
My drum machine is an older one so it has no proper midi functions, but instead I could break up pre-recorded drums and change their microtimings  
Just a thought I thought I'd drop.
